### ISSUE TITLE
The search functionality is broken

### ISSUE THREAD

**Issue by clive-machado** [tron180/json_to_tablular#1]
**Context:**
Since we’ve pushed the code on the last commit 050cf4f184b1e6361b8652e4572176076fbf2296 the search functionality doesn't work as expected.

**Steps to Recreate:**
1) Search "test" on page 1.
2) It will load a set of result.
3) Remove the search text "test"
4) Move to page 2 search "test" again 
5) I get different set of results. 

**Solution or next step:** 
I should receive the same set of search results no matter which page I navigate to.

**Comment by tron180** [comment]
This issue is resolved in the latest version:
0dac012bb0f7aeccddd064728f7f863918213d2b
