### ISSUE TITLE
The pagination should be disabled when list is less than 10

### ISSUE THREAD

**Issue by clive-machado** [tron180/json_to_tablular#2]
**Context:**
Since we’ve pushed the code on the last commit 050cf4f184b1e6361b8652e4572176076fbf2296 the pagination functionality doesn't work as expected along with the search.

**Steps to Recreate:**
1) Search "test" on page 1
2) It displays the results less than 10

**Solution or next step:**
The pagination should be disabled when the results are less than 10

**Comment by tron180** [comment]
The issue has been resolved in the latest commit:
0dac012bb0f7aeccddd064728f7f863918213d2b
